### ISSUE TITLE
Headers or URL Params Break Caching?

### ISSUE THREAD

**Issue by DrLongGhost** [RasCarlito/axios-cache-adapter#104]
I can't get caching to work and the only thing I can think of is that the headers or URL parameters are somehow preventing this from working. I imagine this is probably user error of some sort, but I can't see what I'm doing wrong. Any help would be appreciated.

I'm using the latest version (2.3.3) from npm and here is my code:

```
const setup = require("axios-cache-adapter").setup;
window.axios = setup({
    cache: {
        maxAge: 15 * 60 * 1000,
        //readHeaders: false,
        //ignoreCache: false,
    }
});

// Here is the actual ajax call:

  return axios.get(routesUrl, {
    params: {
      status: $store.state.group.show_inactive_pairs_routes ? '' : 'active',
      groupId: !_.isEmpty(groupId) ? groupId : $store.state.group.nid
    }
  })
```

I've tried it with and without the readHeaders/ignoreCache arguments in the setup arguments. It makes no difference and I cannot get caching to work at all.

I'm using this code in a Vue.js application which has a button that triggers an Ajax call. I would expect to see a network request the first time I click the button, and no network call on the second and subsequent clicks. But, instead, no caching occurs. Ever.

Here is what one of these API calls looks like:

<img width="509" alt="api" src="https://user-images.githubusercontent.com/1702840/60774499-a0108100-a0e2-11e9-9ef0-7a7cab89713e.png">

Any ideas?

**Comment by DrLongGhost** [comment]
I ended up using this cache adapter instead (https://github.com/kuitos/axios-extensions) and it worked right away. I'm pretty sure there is either a bug here or maybe I was doing something wrong with the setup. But if anyone has a similar issue, at least you can try the other project, which worked for me without any issues.

**Comment by RasCarlito** [comment]
Hey @DrLongGhost !

Sorry it took me so long to get back to you. Glad you found another solution that is working for you.

Just in any case someone has this issue, for now, by default `axios-cache-adapter` does not cache requests with query parameters. You can enable query parameter caching using `exclude.query = false` option.

```js
import { setup } from 'axios-cache-adapter'

const axios = setup({
    cache: {
        maxAge: 15 * 60 * 1000,
		exclude: { query: false }
    }
})
```

This will change in v3.

Sorry for this not being very clear in the documentation.

Cheers 🍻

**Comment by RasCarlito** [comment]
Will close issue for now. If you have any extra feedback do give please do 🚀
