### ISSUE TITLE
localforage as cache

### ISSUE THREAD

**Issue by purplekrayons** [RasCarlito/axios-cache-adapter#105]
Referring to your [documentation here](https://github.com/RasCarlito/axios-cache-adapter#use-localforage-as-cache-store), why do you instantiate an instance of localforage every time you make an API call? Is there a reason for that?

Perhaps I am misunderstanding, but wouldn't it be better to create an instance of localforage once? As an example:

```js
import localforage from 'localforage'
import memoryDriver from 'localforage-memoryStorageDriver'
import { setup } from 'axios-cache-adapter'

// Register the custom `memoryDriver` to `localforage`
localforage.defineDriver(memoryDriver)

// Create `localforage` instance
const localforageStore = localforage.createInstance({
    // List of drivers used
    driver: [
        localforage.INDEXEDDB,
        localforage.LOCALSTORAGE,
        memoryDriver._driver
    ],
    // Prefix all storage keys to prevent conflicts
    name: 'my-cache'
})

const api = setup({
    baseURL: 'https://my.api',
    cache: {
        maxAge: 2 * 60 * 1000,          // set cache time to 2 minutes
        exclude: { query: false },      // cache requests with query parameters
        store: localforageStore         // pass `localforage` store to `axios-cache-adapter`
    }
})
```

**Comment by RasCarlito** [comment]
Hi @purplekrayons !

The `configure()` method in the example is only intended to be executed once, sorry that was not very clear. I wanted the examples to be copy/paste.able but you're right it is not very clear.

In the actual apps I usually have an `utils/api.js` file which does the cache setup and exports the instance as a singleton so whenever I `require('utils/api')` I get the same instance.

**Comment by purplekrayons** [comment]
Thanks for the clarification!
