### ISSUE TITLE
Add type definition for RedisStore

### ISSUE THREAD

**Issue by Ragyal** [RasCarlito/axios-cache-adapter#110]
@RasCarlito As mentioned in #63 type definitions for the newly implemented RedisStore are necessary in order to work properly in TypeScript. Otherwise following example would throw an error on the import statement.

```
// example.ts
import { RedisStore, setup } from "axios-cache-adapter";
import redis from "redis";

const client = redis.createClient();
const store = new RedisStore(client);

export const axios = setup({
  baseURL: "https://some.api.com",
  cache: { store }
});
```

Error:
`.../node_modules/axios-cache-adapter/axios-cache-adapter"' has no exported member 'RedisStore'. `

A quick fix would be to add the following line to `axios-cache-adapter.d.ts`:
`export class RedisStore { constructor(client: any, HASH_KEY?: string); }`

For a more precise solution someone with more experience in type definitions should look over this.

**Comment by RasCarlito** [comment]
Fixed in #111
