### ISSUE TITLE
Will this work with a backend service?

### ISSUE THREAD

**Issue by ktalebian** [RasCarlito/axios-cache-adapter#137]
Does this cache adapter work for a NodeJS server? Or is it intended to be used only for front-end usage?

**Comment by AndrewCraswell** [comment]
It does, I actually just did this last week to cache requests executed in an Express API :)

**Comment by mohamedgomran** [comment]
Yes it works, and if you multi instance service you can use it with Redis

**Comment by igorsantos07** [comment]
@ktalebian could just read the.... _readme_ instead of polluting the issue board :)

**Comment by ktalebian** [comment]
This has been addressed, thanks for the useful information everyone.
