### ISSUE TITLE
"Invalid calling object" error in IE11

### ISSUE THREAD

**Issue by erikagiroux** [RasCarlito/axios-cache-adapter#142]
Calls to `isFunction` cause an error on IE11 since the last version.

When lodash functions were transferred to utilities.js, this line was missing from getTag (see https://github.com/lodash/lodash/blob/master/.internal/getTag.js):
```js
const toString = Object.prototype.toString
```

Because of this, `toString` ends up referring to `window.toString` instead of `Object.prototype.toString`.

There could be 3 easy ways to fix this:

1. Add `const toString = Object.prototype.toString` in the `getTag` function
2. Replace `toString.call(value)` with `({}).toString.call(value)`
3. Replace the whole `isFunction` function to reflect the latest changes in lodash (see https://github.com/lodash/lodash/blob/master/isFunction.js). That way, `getTag` won't be called from `isFunction`. However, `isString` could still cause problems for the same reason so it might not be the best solution.

**Comment by AndrewCraswell** [comment]
I just ran into this today. I think option #1 seems like a solid solution.

**Comment by AndrewCraswell** [comment]
This seems like an easy change to make, @erikagiroux would you be willing to submit a PR? I would do it but am limited on time, but I'd be happy to put a $25 bounty on the issue if you have some free time. This is a blocking issue for my team at the moment

**Comment by erikagiroux** [comment]
@AndrewCraswell Sure. I'll do it tomorrow. Let's just hope the PR is processed quickly. 

In the meantime, maybe you could consider using version 2.4.1. This issue only happens since v2.5.0.

**Comment by ChoOo7** [comment]
Hello
Any upate on this case ?
Thanks

**Comment by madisvain** [comment]
Thank you for this library - I'd be also interested about this update.

**Comment by Brain2000** [comment]
I just spent 2 hours tracking the same thing down, and I found you guys hanging out in here.

**Comment by RasCarlito** [comment]
Thanks for all the work put in.
Should now be fixed in latest release https://github.com/RasCarlito/axios-cache-adapter/releases/tag/2.6.0
