### ISSUE TITLE
Note about version incompatibility with certain Axios version in README

### ISSUE THREAD

**Issue by ruzz311** [RasCarlito/axios-cache-adapter#155]
Is the note at the top of the readme about version locking still a thing?  Axios fixed the issue in 0.19.1 and Nestjs just updated their axios reference to 0.19.2.

_Edit: Well, Just noticed that's the per-request override.  I haven't been tracking that one as much but it would still be nice to get some bump sometime soon for the nestjs users_

**Comment by jahead** [comment]
We use 0.19.2 without a problem, but I'd wait until the official word. I do know we had to use axios.default.adapter to get the adapter to conditionally reset, that's not cache's fault but axios arcane resolution logic for the config merge. 
<img width="594" alt="image" src="https://user-images.githubusercontent.com/5070464/93552003-b090dc80-f9b2-11ea-9a72-0e24d4d2ede5.png">

**Comment by RasCarlito** [comment]
Should now be fixed with latest release using axios 0.20.x https://github.com/RasCarlito/axios-cache-adapter/releases/tag/2.6.0
