### ISSUE TITLE
Clear all cache?

### ISSUE THREAD

**Issue by haswent** [RasCarlito/axios-cache-adapter#170]
Is there a way to invalidate all entries from the cache? 

I want to implement an API call from an external system that will invalidate all cache entries so that the next request will make an API call to get new data across all URL's?

**Comment by malydok** [comment]
I wanted to do the same thing to remove all cache after a user logs out and logs in to another account in the same session.

I created the api using `setup` from the library, and when needed simply removed the store, which is a basic object.

```js
// setup api instance
export const api = setup({
  cache: {
    maxAge: 15 * 60 * 1000,
  },
  baseURL: apiUrl,
});

// remove cached resources
api.cache.store = {};
```

This assumes you're using the in-memory cache strategy.

**Comment by haswent** [comment]
Thanks @malydok - don't know why I didn't think of simply setting the cache-store to an empty object

**Comment by DonovanCharpin** [comment]
Hi @malydok, do you re-create another setup where you logout to clear the cache or do you re-use the same instance of your setup?

**Comment by malydok** [comment]
@DonovanCharpin only dropping the `cache.store` object, the instance is not touched.
