### ISSUE TITLE
Type for 'limit' in adapter options is wrong

### ISSUE THREAD

**Issue by sgarciac** [RasCarlito/axios-cache-adapter#183]
Hello, in the type definitions file:

https://github.com/RasCarlito/axios-cache-adapter/blob/master/axios-cache-adapter.d.ts#L37

limit is defined as boolean, but it should be false | number

**Comment by java-james** [comment]
+1
Documentation reading
```
	/**
	 * {Number} Maximum number of cached request (last in, first out queue system),
	 * defaults to `false` for no limit. *Cannot be overridden per request*
	 */
```
Isn't this defaulting to undefined?

**Comment by sgarciac** [comment]
You are right.

**Comment by sgarciac** [comment]
(just to be clear, the issue is that currently one can not set a number)

**Comment by CaptainCodex** [comment]
There has been multiple pull requests for this for half a year. Is the repo owner planning to merge one of them in?

**Comment by RasCarlito** [comment]
Should now be fixed with latest release https://github.com/RasCarlito/axios-cache-adapter/releases/tag/2.6.0
