### ISSUE TITLE
Axios is out of date

### ISSUE THREAD

**Issue by jahead** [RasCarlito/axios-cache-adapter#214]
Axios is now at v0.20.0 and the issues with 0.19.0 seem to have been solved.

**Comment by merobal** [comment]
The latest version now is 0.21.1. Can anyone confirm is it safe to use that version, also update PR #215 to match with that?

**Comment by merobal** [comment]
@RasCarlito any plan to update this?

**Comment by maxwellsmart84** [comment]
bumping this - i was about to use this package but because of this very reason I decided against it.

**Comment by RasCarlito** [comment]
Should be fixed with latest release https://github.com/RasCarlito/axios-cache-adapter/releases/tag/2.6.0

**Comment by Anenth** [comment]
The latest axios is 0.27, @RasCarlito can we bump the version?
