### ISSUE TITLE
README is wrong

### ISSUE THREAD

**Issue by dnuske** [RasCarlito/axios-cache-adapter#225]
Readme document fails to mention that this lib only caches GET calls.

As can be seen on this line of the source code:
https://github.com/RasCarlito/axios-cache-adapter/blob/2.5.0/src/request.js#L19

Please fix that.

**Comment by RasCarlito** [comment]
Should now be fixed in latest release https://github.com/RasCarlito/axios-cache-adapter/releases/tag/2.6.0 thanks to this PR https://github.com/RasCarlito/axios-cache-adapter/pull/128

Documentation is maybe not much clearer yet but I'll be working on making it better 🙂
