### ISSUE TITLE
Permit some config keys to be set per request

### ISSUE THREAD

**Issue by FMCorz** [RasCarlito/axios-cache-adapter#23]
For your consideration, I thought it may be useful to accept the override of some parameters on a request basis. This may not be useful today, but could come handy at some point.

So for your consideration, I would suggest that the `cache` key from the `request` config, is merged on top of the global config of the cache adapter. Example from an adapter wrapping your adapter:

```
if (e.request && (req.cache && req.cache.useOnNetworkError) && !isExcluded)
```

However, in that case I did not merge the configs as I wrapped your code instead.

**Comment by RasCarlito** [comment]
Very good point! This should not be to hard to implement :smiley:
