### ISSUE TITLE
Support for cache skip or invalidation

### ISSUE THREAD

**Issue by FMCorz** [RasCarlito/axios-cache-adapter#24]
In my application, I need to be able to force delete whichever cache I had set. So, I would like to suggest the ability to be able to delete a cached key, without the need to perform the request itself. That is useful when the developer knows that some data is stale, but does not need to request it yet.

In fact, it probably is better to have the option to set the data stale, rather than deleting it. In which case #20 would still work as intended, but a new request would ignore the stale status.

Additionally, it would be useful, if on a request basis, the developer would be able to state that the cache should be ignored if it exists, but the response should be cached when retrieved. Presently, `excludeFromCache` does not allow for ignoring the cached version while overriding the existing one. This is likely to require #23.

Lastly, but that should probably make its way to another issue, my implementation needs to be able to invalidate cache in bulk. I don't know if this should be the responsibility of your adapter, but my use case is that when some data is set, I know that a bunch of other queries' cache has to be marked stale. For example, when the user creates a new todo, I know that the list of todos is invalid. But also the timeline showing the recent todos, and perhaps something else. So, I am marking the request to be part of some groups, and I allow the cache to be invalidated by group name. E.g.:

```
// Prior to requesting the data.

if (!isExcluded && req.cache && req.cache.groups) {
  const groupsCacheKey = '__groups';
  const groupsKeys = (await cacheStore.getItem(groupsCacheKey)) || {};
  let hasSetAny = false;

  for (let group of req.cache.groups) {
    if (!(group in groupsKeys)) {
      groupsKeys[group] = [];
    }
    if (groupsKeys[group].indexOf(uuid) < 0) {
      hasSetAny = true;
      groupsKeys[group].push(uuid);
    }
  }

  // Commit the changes.
  if (hasSetAny) {
    await cacheStore.setItem(groupsCacheKey, groupsKeys);
  }
}

// Perform the request...
```

```
// Cache clearing functions.
const clearCacheByKey = async function(uuid) {
  let result = await cacheStore.getItem(uuid);
  if (result && 'expires' in result) {
    result.expires = 1;
    await cacheStore.setItem(uuid, result);
  }
};

const clearCacheByGroup = async function(group) {
  const groups = (await cacheStore.getItem('__groups')) || {};
  const uuids = groups[group] || [];
  for (let uuid of uuids) {
    await clearCacheByKey(uuid);
  }
};
```

The actions modifying the list of groups are not atomic, which can be an issue, but for now I'm OK to live with it.

**Comment by mofasass** [comment]
I am in the same situation as you, however my solution is was to use vuex to keep track of stale endpoints. Your solution is a lot more elegant. Woud you mind explaining where you get `cacheStore` from? Thank you!

**Comment by FMCorz** [comment]
It's been a while since I looked into this but I believe this is the instance of localForage in `api.store`. See `store` option.

**Comment by ggedde** [comment]
Here is my implementation for invalidation (clear)

```
import { setup } from 'axios-cache-adapter'

export const api = setup({
	cache: {
		maxAge: 15000,
		limit: 20
	}
})

api.cache.clear = function(key, useRegex)
{
	if(!key)
	{
		api.cache.store = {}
	}
	else if(typeof key === 'string')
	{
		for(let storeKey in api.cache.store)
		{
			if(useRegex)
			{
				const regex = new RegExp(key)
				if(regex.test(storeKey))
				{
					delete api.cache.store[storeKey]
				}
			}
			else if(storeKey === key)
			{
				delete api.cache.store[storeKey]
			}
		}
	}
}

export default api
```

Notice Regex for clearing groups
Ex.  
`api.cache.clear('post', true)` For clearing all keys with 'post' in the fetching url

Would be nice to see something like this as part of the Plugin :)

**Comment by RasCarlito** [comment]
Thanks a lot everyone for your input on this!
I haven't been able to work as much as I would want on this lately.

If anyone feels like making a pull request with the modifications I'll gladly merge it!

Else, hope I find some time working on it soon :)

Cheers 🍻

**Comment by jahead** [comment]
Hey guys, 

We have had a need to for a way to invalidate item(s).
Our use case is that we  get requests on ``` [GET] /observations?startDate=<datetime>&endDate=<dateTime>&profile=<string> ``` which we would like to cache. Where profile, startdate annd enddate may vary depending where the user is in the app.

However, when we post observations, we use ``` [POST] /observations ``` to submit observations, we need a way to invalidate all observations requests keys that have ```  /observations ```. With the option to be more smarter in the future. 

We've also been following issue #31 due to the fact that we want the cache key to be query params sensitive. 

We've developed a solution that solves both #31 and #24 by allowing the user to define a invalidate function that gets checked every time a request is made. It has a sane default that is

```
function invalidate (config = {}) {
  if (isFunction(config.invalidate)) return config.invalidate

  return async (cfg, req) => {
    const uuid = cfg.key(req)
    const method = req.method.toLowerCase()
    if (method !== 'get') {
      await cfg.store.removeItem(uuid)
    }
  }
}
```

which maps to the same orginal functionality. 
he initial implemenation is at #54 let me know what we can do to get this mainlined.

**Comment by RasCarlito** [comment]
Hi @jahead !

Thanks for sharing your solution here! I really like your approach in #54, it is simple and elegant.

I will review your pull request as soon as I can to get this integrated.

Thanks for your interest in this project! 😄 

Cheers 🍻

**Comment by jahead** [comment]
Let me know if there's anything we can do to help out
