### ISSUE TITLE
Unable to cache query params

### ISSUE THREAD

**Issue by izmn** [RasCarlito/axios-cache-adapter#31]
I want to cache requests with query params,
but cache always ignore query params, even when I set `exclude.query` to `false`

Example: 

```js
const cache = setupCache({
  maxAge: 15 * 60 * 1000,
  debug: true,
  exclude: {
    query: false
  }
});

const api = axios.create({
  adapter: cache.adapter
});
```

first request: 
```js
api({
  url: 'http://url.to/endpoint',
  params: {
    offset: 0,
    limit: 100
  }
})
.then(res => {
  console.log(res); // works well
})
```
second request:
```js
api({
  url: 'http://url.to/endpoint',
  params: {
    offset: 100,
    limit: 100
  }
})
.then(res => {
  console.log(res); // returns the same response as for first request
})
```

**Comment by miluoshi** [comment]
@izmn You can also include stringified params in cache key:

```javascript
const cache = setupCache({
  exclude: { query: false },
  key: req => req.url + JSON.stringify(req.params)
})
```

**Comment by microstudi** [comment]
I've been in the same issue, just point that @miluoshi solution works except if you are using URLSearchParams as query request in axios. In that case `JSON.stringify` will return an empty string. You will need to add something like this to overcome it:
```javascript
const cache = setupCache({
  maxAge: 15 * 60 * 1000,
  exclude: { query: false },
  key: req => {
    let serialized = req.params instanceof URLSearchParams ? 
      req.params.toString() : JSON.stringify(req.params) || ''
    console.log('cache key', serialized, 'req',req);
    return req.url + serialized
  }
})
```

**Comment by RasCarlito** [comment]
Thanks for the addition @microstudi !

I'll try to include this in the default `key` method. Or if someone wants to post a PR with the modifications 😄

**Comment by microstudi** [comment]
Probably I can do it in a few days!

**Comment by RasCarlito** [comment]
@microstudi I have just one issue with the `req.params instanceof URLSearchParams` condition. I think it will fail in Node.js because `URLSearchParams` does not exist.

Maybe add a `if (URLSearchParams) {}` block to make sure the condition runs in browser and Node.js 😃

**Comment by microstudi** [comment]
ok, thanks! Didn't though about that! hopefully I'll send you the pull request this week!!

**Comment by RasCarlito** [comment]
Hey everyone! So I just posted a PR fixing this bug #59 

Hope it covers all use cases 😄
