### ISSUE TITLE
Current release version depends on axios 0.16

### ISSUE THREAD

**Issue by kosanna** [RasCarlito/axios-cache-adapter#32]
Hi there!

We're using axios-cache-adapter currently and thus rely on axios subdependency which is under the library itself. We'd noticed that the latest master of the cache adapter is already pointed to 0.18, however has not been released yet.

Could you please release it or make a separate release with upgrade to 0.18 as we need a feature that's been added in 0.18.

Thanks.

**Comment by RasCarlito** [comment]
Hi @kosanna 

Sure thing, I'll release a `2.1.0` tag and publish it to npm 😃

**Comment by RasCarlito** [comment]
Here is [the release](https://github.com/RasCarlito/axios-cache-adapter/releases/tag/2.1.0)

If you have other concerns with the library don't hesitate.

Cheers 🍻

**Comment by kosanna** [comment]
Cheers 🍻
