### ISSUE TITLE
Optimize Lodash - Package is importing the entire lodash bundle

### ISSUE THREAD

**Issue by ggedde** [RasCarlito/axios-cache-adapter#38]
When using this this package with Vuejs and Webpack it requires all of lodash. Instead if should just be using a small set of items.  This is causing an extra large lodash bundle in my vendor.js bundle.
I am using it in this method and using the instance of axios pre-configured with the cache adapter
```
import { setup } from 'axios-cache-adapter'

const api = setup({
  cache: {
    maxAge: 15 * 60 * 1000
  }
})
```
Removing this package and just using axios directly resolve the issue.

**Comment by RasCarlito** [comment]
Hi @ggedde !

The `axios-cache-adapter` webpack build is configured to leave out lodash and only require the bits and pieces necessary but I haven't gone as far as inspecting the bundle in a real app using the package, so there is surely room for improvement!

I'll check it out as soon as possible 😃 

Thanks for reporting the issue.

Cheers

**Comment by ggedde** [comment]
Sure thing,
I had a quick look around and for the most part it seems that your are just pulling in only the peices you need, but I did notice on test/spec/request.spec.js that it is pulling in the entire lodash.  However, I would assume that tests would not get compiled into package that I am pulling in, but not sure.  If that is not the issue, then I wonder if it is something else or possibly a typo somewhere in the sub function that your pulling in.

**Comment by RasCarlito** [comment]
Hi @ggedde ! Sorry for not getting back to you any quicker. Had other life priorities 😄 

How did you inspect and find that your bundle contained all of lodash when using `axios-cache-adapter`?

For instance, I just setup a test project with the bare minimum (axios-cache-adapter, webpack, babel) here: https://github.com/RasCarlito/test-axios-cache-adapter

And the generated [dist.js](https://github.com/RasCarlito/test-axios-cache-adapter/blob/master/dist.js) doesn't seem to have all of lodash. There only seems to be references to each single method that `axios-cache-adapter` is using: https://github.com/RasCarlito/test-axios-cache-adapter/blob/master/dist.js#L233

But maybe I'm completely wrong here. Will try with a bundle analyzer

**Comment by ggedde** [comment]
Yeah I was just using the analyzer.
Once I removed your package and ran the analyzer again lodash was gone.

I haven't checked it anytime recently, but I will let you know when I do.

Did you update test/spec/request.spec.js?

**Comment by RasCarlito** [comment]
Ok thanks 😃 

Nope, no particular changes since you found this

**Comment by RasCarlito** [comment]
Ok so after more digging into this I can safely say that not all of lodash is imported by `axios-cache-adapter` 😄 

Complete lodash is **68.98KB** parsed
And the parts loaded by `axios-cache-adapter` add up to **31.58KB** parsed

This is almost half of lodash when only using few methods. But these methods use a lot of other lodash methods themselves.

Will close this issue 🚀 

Cheers
