### ISSUE TITLE
Custom caching options per request

### ISSUE THREAD

**Issue by pavle-lekic-htec** [RasCarlito/axios-cache-adapter#56]
I created and api object, like you described in the docs, but I can only set caching for all requests done by that object. I cannot set specific caching times for different endpoints. I think that would be convenient to have. Because this way I need to create a new "api" object every time I want a different cache lengths.

**Comment by RasCarlito** [comment]
Hi @pavle-lekic-htec !

Actually you already can do this, maybe documentation is not at all clear about this.

You just need to pass a `cache` object to your request definition:
```js
import { setup } from 'axios-cache-adapter'

// Setup cached api with a 15min cache for every request
const api = setup({
  cache: {
    maxAge: 15 * 60 * 1000
  }
})

// Making a request which uses a specific short `maxAge`
const response = api({
  url: 'https://httpbin.org/get',
  method: 'get',
  cache: { maxAge: 1 } // One millisecond cache
})
```

I just made a PR #58 adding a test making sure this works.

**Comment by RasCarlito** [comment]
@pavle-lekic-htec If you have any issue please feel free to re-open this with some more detailed information.

Cheers
