### ISSUE TITLE
Feature request: limit the total number of cached items

### ISSUE THREAD

**Issue by mbsimonovic** [RasCarlito/axios-cache-adapter#6]

**Comment by RasCarlito** [comment]
Hi @mbsimonovic 
How would you need this feature to behave ?
Would it work like a sort of cache queue: last in, first out ?
Let's say the limit is 10 cached requests. The first 10 requests are cached. When the 11th request is made the first cached request is cleared from the cache. Is that what you had in mind ?

Cheers

**Comment by mbsimonovic** [comment]
@RasCarlito exactly. My worry is if theres no limit then i could get out of memory. Time based exipiration does not prevent this.

**Comment by RasCarlito** [comment]
@mbsimonovic I've merged this feature onto the master branch. I'll release the new version this week after adding a bit more tests. Thanks again for the request :beers:

**Comment by RasCarlito** [comment]
@mbsimonovic Actually I just released a new version: [v1.6.0](https://github.com/RasCarlito/axios-cache-adapter/releases/tag/1.6.0)
