### ISSUE TITLE
Implement a redis store

### ISSUE THREAD

**Issue by RasCarlito** [RasCarlito/axios-cache-adapter#63]
Create a store that can write cache entries in redis.

Either create a `RedisStore` (similar to `MemoryStore` already provided) or just an example of how to provide a custom `store` option that will use redis.

**Comment by mohamedgomran** [comment]
@RasCarlito I can work on this with my colleague, Do we have to wait for V3 or just start now?

**Comment by RasCarlito** [comment]
Hey @mohamedgomran !

Sorry for not getting back to you earlier. No need to wait for V3, I have no plan to change the `store` mechanism for now.

If you need any help I'll do my best answering any of your questions 😃 

Cheers 🍻

**Comment by Ragyal** [comment]
@mohamedgomran I think there are missing exported type definitions.

When using Typescript I can not import RedisStore:
`.../node_modules/axios-cache-adapter/axios-cache-adapter"' has no exported member 'RedisStore'. ts(2305)`

Would be nice if that could be fixed.

**Comment by mohamedgomran** [comment]
@Ragyal It's exportes the same way `setupCache`, Please note that `RedisStore` only available in server-side. If you are facing this issue in server-side please share an example to reproduce it with `ts`.

**Comment by Ragyal** [comment]
@mohamedgomran Here is an NodeJS exmaple in TS:
```// example.ts
import { RedisStore, setup } from "axios-cache-adapter";
import redis from "redis";

const client = redis.createClient();
const store = new RedisStore(client);

export const axios = setup({
  baseURL: "https://some.api.com",
  cache: { store }
});
```

**Comment by RasCarlito** [comment]
Hey @Ragyal! Thanks for reporting this.

We should open it as a new issue, maybe you'd also be willing to submit a PR with your solution which will do for now IMO 😄
