### ISSUE TITLE
make serializeQuery exported

### ISSUE THREAD

**Issue by FyiurAmron** [RasCarlito/axios-cache-adapter#66]
currently, default implementation of `key` uses `serializeQuery` - but for simple extension, one can either provide a simple string prefix, or provide an own function; there's no way to e.g. provide
`key: req => req.url + serializeQuery(req.params),`, as given in the docs, because `serializeQuery` is not exported from `cache` module.

exporting serializeQuery would solve this and allow e.g. `key: req => req.url + serializeQuery(req.params) + req.headers['foo']` etc. in client code.

**Comment by RayPS** [comment]
Try this https://github.com/RasCarlito/axios-cache-adapter/issues/70#issuecomment-463473311

**Comment by FyiurAmron** [comment]
@RayPS thanks, but I am well aware of QS parsers; still, using them is essentially importing Yet Another Node Module, which is IMVHO an overkill when I only need to supply simple default query serialization for a cache key *which is actually provided by the package I use, only not accessible from outside*...

**Comment by RasCarlito** [comment]
Hi @FyiurAmron !

Thanks for your suggestion, just opened a PR with the change.

What do you think?

**Comment by FyiurAmron** [comment]
@RasCarlito it's great - many thanks for implementing this change, mate!

**Comment by FyiurAmron** [comment]
(I'm leaving this opened until the #73 is merged and available in stable channel)
