### ISSUE TITLE
Error on tests (jest)

### ISSUE THREAD

**Issue by Needled** [RasCarlito/axios-cache-adapter#67]
Hi,
I tried to adapt the axios-cache-adapter to an existing node project where the usage seemed relevant. I am getting however a "typeError: Cannot read property adapter of undefined" which seems to be coming directly from this repo and happens whether I use the cache adapter or not (just from importing the module) during test execution. Everything seems to be working fine during compile/build however, I am only facing issues with testing.
![image](https://user-images.githubusercontent.com/8711645/52335023-9d114780-2a01-11e9-9395-aa01385e2a8e.png)
Do you have some suggestion on how to bypass/mitigate this issue?

**Comment by RasCarlito** [comment]
Hey @Needled ! Sorry for not getting back to you on this topic.

Did you manage to solve the issue?

**Comment by Needled** [comment]
Hi,
Yes, this was developed by someone else so I was confused. The problem was the way jest mocks API calls. Basically, it disregards completely the module and just returns prepared data depending on the parameters specified. So the solution was to move the manual mock over the API call to the cache-adapter instead of axios [ since now you are doing api.get() instead of axios.get() ]. Didn't seem to solve everything completely but at least now it makes sense why it's failing :)

**Comment by RasCarlito** [comment]
If you have any suggestion we could incorporate into `axios-cache-adapter` don't hesitate
