### ISSUE TITLE
Empty params when use with paramsSerializer

### ISSUE THREAD

**Issue by RayPS** [RasCarlito/axios-cache-adapter#70]
https://github.com/RasCarlito/axios-cache-adapter/blob/684139d3dc465bb5178b176a6908d50c7c907e4d/src/cache.js#L102

```javascript
axios.get('/user', {
  paramsSerializer: params => {
    // custom paramsSerializer
    return params
  },
  params: {
    ID: 12345
  }
}).then(response => {
  console.log(response.config.params)
})
```
**Console**:
`▶︎ URLSearchParams {}`

**Comment by RasCarlito** [comment]
Hey @RayPS !

Thanks for reporting this issue, will try to look into it ASAP 😃

**Comment by RayPS** [comment]
I have found a temporary workaround for anyone who facing the same issue.

Replace the buggy serializeQuery with QS instead.
https://www.npmjs.com/package/qs
```javascript
import qs from 'qs'

const paramsSerializer = params => {
  return qs.stringify(params)
}
```

```javascript
const cache = setupCache({
  // Other configurations
  key: req => req.url + paramsSerializer(req.params),
})
```

**Comment by JonDum** [comment]
Thanks @RayPS! Ran into this as well (we use jsurl to serialize params). Found it pretty odd that the cache key hasher would interfere with the `paramSerializer` that axios is given, but your workaround fixes it
