### ISSUE TITLE
Use it with Vue-axios

### ISSUE THREAD

**Issue by moas** [RasCarlito/axios-cache-adapter#74]
Hello,

Please can you give me an example of vue-axios and axios!-cache-adapter integration ?!

My current implementation which not works:

`const axiosCache = setupCache({
  maxAge: 15 * 60 * 1000
})
Vue.use(VueAxios, axios)
Vue.axios.defaults.baseURL = 'hhtps://api.net'
Vue.axios.defaults.headers.common['Authorization'] = "Token xxxxx"
Vue.axios.defaults.adapter = axiosCache.adapter`

Merci

**Comment by RasCarlito** [comment]
Hi @moas !

I've never used Vue but I'll try to look into it 😄 

I'll get back to you.

Cheers

**Comment by sloba88** [comment]
Here is how to use it with Vue:
```
import VueAxios from 'vue-axios'
import axios from 'axios'
import { setupCache } from 'axios-cache-adapter'

const cache = setupCache({
  maxAge: 15 * 60 * 1000
})
Vue.use(VueAxios, axios)
Vue.axios.defaults.adapter = cache.adapter
```

**Comment by ollasm** [comment]
What 's the difference  between your code and my example paste in first issue message ?

**Comment by sloba88** [comment]
That's a good point, I didn't notice that it's the same.

But it does work for me, I checked again and it's caching.

Is it throwing any errors or it just doesn't work?
Are you then using axios for get requests like this ```this.axios.get()``` ?

**Comment by RasCarlito** [comment]
Thanks @sloba88 for helping out. As said earlier I've never used Vue but it seems to me that overriding the axios default adapter works but is not the best practice.

I would see it more like this:
```js
import VueAxios from 'vue-axios'
import { setup } from 'axios-cache-adapter'

// Use `setup` method which gives an axios instance with cache pre-configured
const axiosInstance = setup({
  cache: {
    maxAge: 15 * 60 * 1000
  }
})

Vue.use(VueAxios, axiosInstance)
```

This should be equivalent to your example but does not modify the base axios instance.

Anyway, this is not helping as to knowing why it does not work for @moas 😅

**Comment by moas** [comment]
Hi
My request code snippet
```
      let a = Vue.axios.get('/a/')
      let b = Vue.axios.get('b/')
      try {
        Vue.axios.all([a, b]).then(
          Vue.axios.spread((aRet, bRet) => {
          })
        ).catch((e) => {
          console.log(e)
        })
      } catch (error) {
        console.log(error)
      }
```
Error logged in console:
```
TypeError: vue__WEBPACK_IMPORTED_MODULE_1__.default.axios.all is not a function
    at Store.initApp (index.js?99cf:51)
    at Array.wrappedActionHandler (vuex.esm.js?2f62:721)
    at Store.dispatch (vuex.esm.js?2f62:428)
    at Store.boundDispatch [as dispatch] (vuex.esm.js?2f62:322)
    at VueComponent.mounted (initApp.vue?9cab:42)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1854)
    at callHook (vue.runtime.esm.js?2b0e:4194)
    at Object.insert (vue.runtime.esm.js?2b0e:3132)
    at invokeInsertHook (vue.runtime.esm.js?2b0e:6311)
    at Vue.patch [as __patch__] (vue.runtime.esm.js?2b0e:6530)
```

**Comment by RasCarlito** [comment]
Hey @moas I think I understand why your request snippet does not work.

The `axios.all()` method only exists on the core axios object.

See this REPL test I did
```
~/www/axios-cache-adapter
❯ node
> const axios = require('axios')
undefined
> axios.all
[Function: all]
> const api = axios.create()
undefined
> api.all
undefined
```

So if you use the `axios-cache-adapter` `setup()` method like I suggested (which uses `axios.create()`) you won't have access to the `axios.all()` method.

If that is the only issue you have then you should consider using `Promise.all()` instead like:

```js
Promise.all([
  Vue.axios.get('/a'),
  Vue.axios.get('/b')
]).then(([responseA, responseB]) => {
  // Do something with responses
})
```

You don't need `axios.spread()` just destructure the array like I did in the example above.

If you do have other issues can you please detail them a bit more?

Cheers 😄

**Comment by RasCarlito** [comment]
Closing this. Feel free to re-open if needed.
