### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by tejovanthWork** [RasCarlito/axios-cache-adapter#85]
Is there any support for typescript? 
Even [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) doesn't yield anything in this direction.

**Comment by RasCarlito** [comment]
Hi @tejovanthWork !

No specific support for typescript sorry. I'm not much of a fan of typescript.

But if you'd like to contribute something to make `axios-cache-adapter` more compatible with typescript I'd be glad to help and review your PR.

Cheers 🍻

**Comment by charjac** [comment]
the .d.ts file seem to be missing in the installation folder under node_modules.
but the line in the package.json file is here:

"types": "axios-cache-adapter.d.ts",

**Comment by tejovanthWork** [comment]
Thanks @charjac :)
I'll close this now.

**Comment by RasCarlito** [comment]
Released as version [2.3.2](https://github.com/RasCarlito/axios-cache-adapter/releases/tag/2.3.2) 🚀
