### ISSUE TITLE
Config Property: Disable cache

### ISSUE THREAD

**Issue by crutch12** [RasCarlito/axios-cache-adapter#88]
Let don't use cache at all if config has special property.

For example:
`{
  disable: true, // or function, which has access to config and request
}`

Reason:

I use Vuex + ssr, so all requests from ssr write in store and whole this data comes back on the front. I don't need the most of this data in store, I need only a part.
So I want to set `disable: true` for all request and in some places write `disable: false`

I tried use `invalidate`, but `invalidate` works later than `setItem` method

Thx

**Comment by crutch12** [comment]
Okay, I did it using `exclude.filter => true`, and set per request `exclude.filter => false`, but it was hard :)

exclude.filter doesn't have access to cache config, so it won't work in every case

**Comment by RasCarlito** [comment]
Hi @crutch12 !

Sorry the `exclude.filter` documentation is not very clear. You could filter out those SSR requests through different means.

```js
import { setup } from 'axios-cache-adapter';

const api = setup({
  cache: {
    exclude: {
      // Use filter method to inspect axios request. Return `true` to exclude request from cache
      filter: (req) => req.url.match(/my-awesome-regex/),
      // As matching against the request url is common we can just pass a list of regexs in `paths` option
      paths: [
        /my-awesome-regex/
      ],
      // Or excluding all paths which contain query string parameters (true by default)
      query: true
    }
  }
})
```

I am working to maybe make it simpler in the v3. Maybe just a middleware list which each receive the cache config and the axios request.

If you have any suggestions it'd be awesome :rocket: 

Cheers :beers:
