### ISSUE TITLE
ES6 babel array func，cause of     "@tusbar/cache-control": "0.3.1",

### ISSUE THREAD

**Issue by tangxiaolang101** [RasCarlito/axios-cache-adapter#89]
`/*!*****************************************************!*\
  !*** ./node_modules/@tusbar/cache-control/index.js ***!
  \*****************************************************/
/*! no static exports found */function(e,t){const r=/([a-zA-Z][a-zA-Z_-]*)\s*(?:=(?:"([^"]*)"|([^ \t",;]*)))?/g,n={maxAge:"max-age",sharedMaxAge:"s-maxage",maxStale:"max-stale",minFresh:"min-fresh",immutable:"immutable",mustRevalidate:"must-revalidate",noCache:"no-cache",noStore:"no-store",noTransform:"no-transform",onlyIfCached:"only-if-cached",private:"private",proxyRevalidate:"proxy-revalidate",public:"public"};function i(e){return null===e}function o(e){if(!e)return null;const t=parseInt(e,10);return!Number.isFinite(t)||t<0?null:t}class a{constructor(){this.maxAge=null,this.sharedMaxAge=null,this.maxStale=null,this.maxStaleDuration=null,this.minFresh=null,this.immutable=null,this.mustRevalidate=null,this.noCache=null,this.noStore=null,this.noTransform=null,this.onlyIfCached=null,this.private=null,this.proxyRevalidate=null,this.public=null}parse(e){if(!e||0===e.length)return this;const t={},a=e.match(r)||[];return Array.prototype.forEach.call(a,e=>{const r=e.split("=",2),[n]=r;let i=null;r.length>1&&(i=r[1].trim()),t[n.toLowerCase()]=i}),this.maxAge=o(t[n.maxAge]),this.sharedMaxAge=o(t[n.sharedMaxAge]),this.maxStale=i(t[n.maxStale]),this.maxStaleDuration=o(t[n.maxStale]),this.maxStaleDuration&&(this.maxStale=!0),this.minFresh=o(t[n.minFresh]),this.immutable=i(t[n.immutable]),this.mustRevalidate=i(t[n.mustRevalidate]),this.noCache=i(t[n.noCache]),this.noStore=i(t[n.noStore]),this.noTransform=i(t[n.noTransform]),this.onlyIfCached=i(t[n.onlyIfCached]),this.private=i(t[n.private]),this.proxyRevalidate=i(t[n.proxyRevalidate]),this.public=i(t[n.public]),this}format(){const e=[];return this.maxAge&&e.push(`${n.maxAge}=${this.maxAge}`),this.sharedMaxAge&&e.push(`${n.sharedMaxAge}=${this.sharedMaxAge}`),this.maxStale&&(this.maxStaleDuration?e.push(`${n.maxStale}=${this.maxStaleDuration}`):e.push(n.maxStale)),this.minFresh&&e.push(`${n.minFresh}=${this.minFresh}`),this.immutable&&e.push(n.immutable),this.mustRevalidate&&e.push(n.mustRevalidate),this.noCache&&e.push(n.noCache),this.noStore&&e.push(n.noStore),this.noTransform&&e.push(n.noTransform),this.onlyIfCached&&e.push(n.onlyIfCached),this.private&&e.push(n.private),this.proxyRevalidate&&e.push(n.proxyRevalidate),this.public&&e.push(n.public),e.join(", ")}}function s(e){const t=new a;return t.parse(e)}function c(e){return e instanceof a?e.format():a.prototype.format.call(e)}e.exports={CacheControl:a,parse:s,format:c}},"./node_modules/core-js/modules/_a-function.js":`

We use ·axios-cache-adapter·. Some modules have Array Func, so low version Android Ph caught an error.

I check `axios-cache-adapter`'s packjson, I find     "@tusbar/cache-control": "0.3.1" this module not babel.

**Comment by immortal1070** [comment]
Hi! Possibly https://github.com/RasCarlito/axios-cache-adapter/pull/90 will solve the issue

**Comment by RasCarlito** [comment]
Hi @tangxiaolang101 !

Thanks for reporting this. Maybe it is fixed with the latest release [2.3.1](https://github.com/RasCarlito/axios-cache-adapter/releases/tag/2.3.1).

Could you check and tell me?

Cheers 🍻

**Comment by RasCarlito** [comment]
Will close as for me this should be fixed. Feel free to re-open if that is not the case.

Cheers
