### ISSUE TITLE
Config override per request doesn't work

### ISSUE THREAD

**Issue by mohamedgomran** [RasCarlito/axios-cache-adapter#99]
Axios allow only some keys to be passed in request config check them here https://github.com/axios/axios/blob/master/lib/core/mergeConfig.js

Unfortunately `cashe` is not one of these keys, so the function `mergeRequestConfig` receive `req` parameter without `cache` object and the default cache config isn't overridden.

**Comment by RasCarlito** [comment]
Oh damn, I think this was not the case before as I know the per request cache config worked.

**Comment by mohamedgomran** [comment]
This is due to the axios last update v0.19, they released it a couple of weeks ago.

**Comment by mohamedgomran** [comment]
It's going to be solved in this PR https://github.com/axios/axios/issues/2203

**Comment by GMaiolo** [comment]
Any news on this?

**Comment by AndrewCraswell** [comment]
This is being tracked in the https://github.com/axios/axios/pull/2207 PR now. They merged the changes this week but haven't released due to some test failures.

**Comment by ilyaskorik** [comment]
Is this actual ?

**Comment by sramam** [comment]
seems v0.19.2 fixes this: https://github.com/axios/axios/compare/v0.19.1...v0.19.2
Any chance of a new release for axios-cache-adapter?

**Comment by EvanLovely** [comment]
Yep, looks it's been merged: https://github.com/axios/axios/pull/2207

**Comment by EvanLovely** [comment]
Hmm... 🤔 the `package.json` says it's been updated: 

https://github.com/RasCarlito/axios-cache-adapter/blob/137f392ffcfe1a3d00a2e950f0317130bb44b2e7/package.json#L82-L84

**Comment by burnoo** [comment]
It's working, but haven't been released yet. You can install new version by:
```bash
yarn remove axios-cache-adapter
yarn add RasCarlito/axios-cache-adapter
```

**Comment by elamperti** [comment]
Workaround for anyone else trying this with axios 0.20 or above: instead of using `setup` just use axios.create + `setupCache`, so it doesn't rely on the axios version stated in the package.json of this cache adapter.

**Comment by victors1681** [comment]
it's working fine with axios 0.19.2 https://codesandbox.io/s/axios-cache-api-testing-wk3o4

**Comment by lobosan** [comment]
is this still an issue?

**Comment by jahead** [comment]
We use 0.19.2 without a problem. 
I do know we had to use axios.default.adapter to get the adapter to conditionally reset, that's not cache's fault but axios arcane resolution logic for the config merge.
```
    const response = await Instance.get(uri, {
      adapter: axios.defaults.adapter,
      validateStatus: status =>
        (status >= 200 && status < 300) || (status >= 401 && status <= 404),
    });
```
I think axios 0.20, changes this again.

**Comment by nolde** [comment]
What is the current state of this issue? Can it be used with axios versions above 0.18.1? Has the package version been fixed, to avoid having multiple versions of axios being used?

**Comment by RasCarlito** [comment]
Should now be fixed with lastest release https://github.com/RasCarlito/axios-cache-adapter/releases/tag/2.6.0
